//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
namespace GameFrameWork.SingleInstance
{
    public class MonoSingleInstanceNoCreate<T> : MonoBehaviour where T:MonoBehaviour
    {
        protected Transform m_transform = null;
        public Transform mTransform
        {
            get
            {
                return m_transform;
            }
        }
        protected virtual void Awake()
        {
            s_instance = GetComponent<T>();
            if (s_instance == null)
                s_instance = gameObject.AddComponent<T>();
            m_transform = transform;
        }
        static T s_instance = null;
        public static T GetInstance()
        {
            return s_instance;
        }
        
        public static T Instance
        {
            get { return GetInstance(); }
        }
        protected virtual void OnRelease()
        {

        }

        public void OnDestroy()
        {
            if (s_instance != null)
                OnRelease();
            s_instance = null;
            m_transform = null;
        }
    }
}

