// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CommonEnum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Common.Proto {

  /// <summary>Holder for reflection information generated from CommonEnum.proto</summary>
  public static partial class CommonEnumReflection {

    #region Descriptor
    /// <summary>File descriptor for CommonEnum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommonEnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBDb21tb25FbnVtLnByb3RvKrMBCg1FcXVpcFR5cGVFbnVtEgwKCFNob3Vs",
            "ZGVyEAASCgoGSGVsbWV0EAESDAoITmVja2xhY2UQAhIJCgVXcmlzdBADEgoK",
            "BkphY2tldBAEEgoKBkdsb3ZlcxAFEggKBEJlbHQQBhIMCghUcm91c2VycxAH",
            "EgsKB3dlYXBvbnMQCBINCglPcm5hbWVudHMQCRIJCgVTaG9lcxAKEgoKBlNo",
            "aWVsZBALEgwKCEVxdWlwTUFYEAwqIQoWQ2hhcmFjdGVyQXR0cmlidXRlRW51",
            "bRIHCgNFeHAQACo0CgxJdGVtVHlwZUVudW0SDAoIQ3VycmVuY3kQABIWChJD",
            "aGFyYWN0ZXJBdHRyaWJ1dGUQASpaChBDdXJyZW5jeVR5cGVFbnVtEggKBEdv",
            "bGQQABILCgdEaWFtb25kEAESDAoIVHJlYXN1cmUQAhIQCgxUaW1lU2tpcEl0",
            "ZW0QAxIPCgtDdXJyZW5jeU1BWBAEKr0CChFBdHRyaWJ1dGVUeXBlRW51bRIJ",
            "CgVTUEVFRBAAEggKBExJRkUQARIKCgZBVFRBQ0sQAhIKCgZERUZFTkQQAxIL",
            "CgdWQU1QSVJFEGUSDwoLUkVUQUxJQVRJT04QZhIJCgVDT01CTxBnEgkKBURP",
            "REdFEGgSCQoFQkxBU1QQaRIMCghLTk9DS09VVBBqEhQKD05FR0xFQ1RfVkFN",
            "UElSRRDJARIYChNORUdMRUNUX1JFVEFMSUFUSU9OEMoBEhIKDU5FR0xFQ1Rf",
            "Q09NQk8QywESEgoNTkVHTEVDVF9ET0RHRRDMARISCg1ORUdMRUNUX0JMQVNU",
            "EM0BEhUKEE5FR0xFQ1RfS05PQ0tPVVQQzgESCwoGQlJVVEFMEK0CEgwKB0NI",
            "QVJJVFkQrgISEAoLTk9UUkVBVE1FTlQQrwIqcAoHUXVhbGl0eRIJCgVXcml0",
            "ZRAAEgkKBUdyZWVuEAESCAoEQmx1ZRACEgoKBlB1cnBsZRADEgoKBlllbGxv",
            "dxAEEgoKBm9yYW5nZRAFEgcKA1JlZBAGEggKBFBpbmsQBxIOCgpRdWFsaXR5",
            "TUFYEAhCD6oCDENvbW1vbi5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Common.Proto.EquipTypeEnum), typeof(global::Common.Proto.CharacterAttributeEnum), typeof(global::Common.Proto.ItemTypeEnum), typeof(global::Common.Proto.CurrencyTypeEnum), typeof(global::Common.Proto.AttributeTypeEnum), typeof(global::Common.Proto.Quality), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ////装备位置
  /// </summary>
  public enum EquipTypeEnum {
    /// <summary>
    ///护肩	
    /// </summary>
    [pbr::OriginalName("Shoulder")] Shoulder = 0,
    /// <summary>
    ///头盔
    /// </summary>
    [pbr::OriginalName("Helmet")] Helmet = 1,
    /// <summary>
    ///项链
    /// </summary>
    [pbr::OriginalName("Necklace")] Necklace = 2,
    /// <summary>
    ///护腕
    /// </summary>
    [pbr::OriginalName("Wrist")] Wrist = 3,
    /// <summary>
    ///上衣
    /// </summary>
    [pbr::OriginalName("Jacket")] Jacket = 4,
    /// <summary>
    ///手套
    /// </summary>
    [pbr::OriginalName("Gloves")] Gloves = 5,
    /// <summary>
    ///腰带
    /// </summary>
    [pbr::OriginalName("Belt")] Belt = 6,
    /// <summary>
    ///裤子
    /// </summary>
    [pbr::OriginalName("Trousers")] Trousers = 7,
    /// <summary>
    ///武器
    /// </summary>
    [pbr::OriginalName("weapons")] Weapons = 8,
    /// <summary>
    ///饰品
    /// </summary>
    [pbr::OriginalName("Ornaments")] Ornaments = 9,
    /// <summary>
    ///鞋子
    /// </summary>
    [pbr::OriginalName("Shoes")] Shoes = 10,
    /// <summary>
    ///护盾
    /// </summary>
    [pbr::OriginalName("Shield")] Shield = 11,
    [pbr::OriginalName("EquipMAX")] EquipMax = 12,
  }

  public enum CharacterAttributeEnum {
    /// <summary>
    ///经验
    /// </summary>
    [pbr::OriginalName("Exp")] Exp = 0,
  }

  public enum ItemTypeEnum {
    /// <summary>
    ///货币类型
    /// </summary>
    [pbr::OriginalName("Currency")] Currency = 0,
    /// <summary>
    ///人物属性
    /// </summary>
    [pbr::OriginalName("CharacterAttribute")] CharacterAttribute = 1,
  }

  public enum CurrencyTypeEnum {
    /// <summary>
    ///金币
    /// </summary>
    [pbr::OriginalName("Gold")] Gold = 0,
    /// <summary>
    ///钻石
    /// </summary>
    [pbr::OriginalName("Diamond")] Diamond = 1,
    /// <summary>
    ///宝箱
    /// </summary>
    [pbr::OriginalName("Treasure")] Treasure = 2,
    /// <summary>
    ///加速券
    /// </summary>
    [pbr::OriginalName("TimeSkipItem")] TimeSkipItem = 3,
    [pbr::OriginalName("CurrencyMAX")] CurrencyMax = 4,
  }

  public enum AttributeTypeEnum {
    /// <summary>
    ///速度
    /// </summary>
    [pbr::OriginalName("SPEED")] Speed = 0,
    /// <summary>
    ///生命
    /// </summary>
    [pbr::OriginalName("LIFE")] Life = 1,
    /// <summary>
    ///攻击
    /// </summary>
    [pbr::OriginalName("ATTACK")] Attack = 2,
    /// <summary>
    ///防御
    /// </summary>
    [pbr::OriginalName("DEFEND")] Defend = 3,
    /// <summary>
    ///吸血
    /// </summary>
    [pbr::OriginalName("VAMPIRE")] Vampire = 101,
    /// <summary>
    ///反击
    /// </summary>
    [pbr::OriginalName("RETALIATION")] Retaliation = 102,
    /// <summary>
    ///连击
    /// </summary>
    [pbr::OriginalName("COMBO")] Combo = 103,
    /// <summary>
    ///闪避
    /// </summary>
    [pbr::OriginalName("DODGE")] Dodge = 104,
    /// <summary>
    ///暴击
    /// </summary>
    [pbr::OriginalName("BLAST")] Blast = 105,
    /// <summary>
    ///击晕
    /// </summary>
    [pbr::OriginalName("KNOCKOUT")] Knockout = 106,
    /// <summary>
    ///忽略吸血
    /// </summary>
    [pbr::OriginalName("NEGLECT_VAMPIRE")] NeglectVampire = 201,
    /// <summary>
    ///忽略反击
    /// </summary>
    [pbr::OriginalName("NEGLECT_RETALIATION")] NeglectRetaliation = 202,
    /// <summary>
    ///忽略连击
    /// </summary>
    [pbr::OriginalName("NEGLECT_COMBO")] NeglectCombo = 203,
    /// <summary>
    ///忽略闪避
    /// </summary>
    [pbr::OriginalName("NEGLECT_DODGE")] NeglectDodge = 204,
    /// <summary>
    ///忽略暴击
    /// </summary>
    [pbr::OriginalName("NEGLECT_BLAST")] NeglectBlast = 205,
    /// <summary>
    ///忽略击晕
    /// </summary>
    [pbr::OriginalName("NEGLECT_KNOCKOUT")] NeglectKnockout = 206,
    /// <summary>
    ///暴虐
    /// </summary>
    [pbr::OriginalName("BRUTAL")] Brutal = 301,
    /// <summary>
    ///仁爱
    /// </summary>
    [pbr::OriginalName("CHARITY")] Charity = 302,
    /// <summary>
    ///禁疗
    /// </summary>
    [pbr::OriginalName("NOTREATMENT")] Notreatment = 303,
  }

  /// <summary>
  ////物品品质
  /// </summary>
  public enum Quality {
    /// <summary>
    ///白色
    /// </summary>
    [pbr::OriginalName("Write")] Write = 0,
    /// <summary>
    ///绿色
    /// </summary>
    [pbr::OriginalName("Green")] Green = 1,
    /// <summary>
    ///蓝色
    /// </summary>
    [pbr::OriginalName("Blue")] Blue = 2,
    /// <summary>
    ///紫色
    /// </summary>
    [pbr::OriginalName("Purple")] Purple = 3,
    /// <summary>
    ///黄色
    /// </summary>
    [pbr::OriginalName("Yellow")] Yellow = 4,
    /// <summary>
    ///橙色
    /// </summary>
    [pbr::OriginalName("orange")] Orange = 5,
    /// <summary>
    ///红色
    /// </summary>
    [pbr::OriginalName("Red")] Red = 6,
    /// <summary>
    ///粉色
    /// </summary>
    [pbr::OriginalName("Pink")] Pink = 7,
    [pbr::OriginalName("QualityMAX")] Max = 8,
  }

  #endregion

}

#endregion Designer generated code
