// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MessageEnum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Common.Proto {

  /// <summary>Holder for reflection information generated from MessageEnum.proto</summary>
  public static partial class MessageEnumReflection {

    #region Descriptor
    /// <summary>File descriptor for MessageEnum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageEnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFNZXNzYWdlRW51bS5wcm90byovCgtNZXNzYWdlRW51bRIPCgtKb2luR2Ft",
            "ZVJlcRAAEg8KC0pvaW5HYW1lUmVzEAFCD6oCDENvbW1vbi5Qcm90b2IGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Common.Proto.MessageEnum), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ////装备位置
  /// </summary>
  public enum MessageEnum {
    [pbr::OriginalName("JoinGameReq")] JoinGameReq = 0,
    [pbr::OriginalName("JoinGameRes")] JoinGameRes = 1,
  }

  #endregion

}

#endregion Designer generated code
