//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.19408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System.IO;

namespace GameFrameWork.DebugTools
{
    internal class DebugLogSaveFile
    {

        public StreamWriter m_w;
        public int m_index;
        public string m_foldName = "";
        static string s_foldPath ="";
        public DebugLogSaveFile(int index, string foldName)
        {
            m_index = index;
            m_foldName = foldName;
            string path = GetPath();
            if (DebugHelper.DebugWork && DebugHelper.ShowWindow) 
                    DebugManager.GetInstance().AddData(DebugTypeEnum.Base, "log file path is = " + path);
            string p = GetFoldPath();
            if (!Directory.Exists(p))
            {
                if (DebugHelper.DebugWork && DebugHelper.ShowWindow)
                    DebugManager.GetInstance().AddData(DebugTypeEnum.Base, "Directory.Exists(p) =" + p);
                Directory.CreateDirectory(p);
            }
            if (!Directory.Exists(p + "/" + m_foldName))
                Directory.CreateDirectory(p + "/" + m_foldName);
            m_w = new StreamWriter(path);
        }
        public void Save()
        {
            m_w.Close();
        }
        public void Write(string path)
        {
            m_w.WriteLine(path);
        }
        public long GetSize()
        {
            return m_w.BaseStream.Length;
        }
        private string GetPath()
        {
            string path = "";

            string name = "/{1}/Debug_log{0}.txt";
            name = string.Format(name, m_index, m_foldName);


#if UNITY_STANDALONE_WIN || UNITY_EDITOR
            path = GetFoldPath() + name;
#elif UNITY_ANDROID
           path = GetFoldPath() + name;
#elif UNITY_IOS

#endif



            return path;
        }

        private string GetFoldPath()
        {
            if (string.Equals(s_foldPath, string.Empty))
            {
#if UNITY_STANDALONE_WIN || UNITY_EDITOR
                s_foldPath = UnityEngine.Application.dataPath + "/../log";
#elif UNITY_ANDROID
                s_foldPath = UnityEngine.Application.persistentDataPath + "/log";
#elif UNITY_IOS

#endif
            }
            return s_foldPath;
        }

    }
}


